export const DOCENTE_PRACTICA = {
    titulo: 'docente',
    tipo_formulario: 'mini',
    modelo: 'DocentePractica',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'form-col2',
            nombre: 'docDocente',
            label_i18n: 'docDocente',
            placeholder_i18n: 'docDocente',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'button',
            claseGrid: 'form-col2',
            nombre: 'BusquedaBoton',
            claseBoton: 'btn btn-primary btn-sm',
            icono: 'search',
            label_i18n: 'buscar',
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Nombre',
            claseGrid: 'form-col1',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Vinculacion',
            claseGrid: 'form-col1',
            label_i18n: 'vinculacion',
            placeholder_i18n: 'vinculacion',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Correo',
            claseGrid: 'form-col1',
            label_i18n: 'correo',
            placeholder_i18n: 'correo',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Telefono',
            claseGrid: 'form-col1',
            label_i18n: 'telefono',
            placeholder_i18n: 'telefono',
            deshabilitar: true,
        },
        {
            etiqueta: 'button',
            tipo: 'button',
            nombre: 'AgregarDocente',
            claseGrid: 'form-col2 ',
            claseBoton: 'form-field',
            label_i18n: 'agregar_docente',
            resultado: true,
            requerido: true,
        },
    ]
}